<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class ProjectStep extends Model
{
    protected $fillable = [
        'end', 'action', 'completed', 'object', 'project_id',
    ];
    protected $dates = [
        'end', 'fact_end',
    ];
    public function fill(array $attributes)
    {
        if ($completed = \Arr::pull($attributes, 'completed')) {
        }
        return parent::fill($attributes); // TODO: Change the autogenerated stub
    }

    public function project() : BelongsTo
    {
        return $this->belongsTo(RegionProject::class, 'project_id');
    }

    public function complete() {
        $this->fact_end = Carbon::now();
        $this->completed = true;
        $this->save();
    }
}
